# Services required for Drupal - Apache, PHP-FPM, MySQL

version: '2'

services:
# Apache image.
  apache:
    build:
      context: ./docker/drupal-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    links:
      - php
    container_name: drupal-apache

# PHP image.
  php:
    build:
      context: ./docker/drupal-phpfpm
    ports:
      - "9001"
    volumes:
      - .:/var/www
      - ~/.composer/cache:/composer/cache
    links:
      - mysql
    container_name: drupal-php

# MySQL image.
  mysql:
    build:
      context: ./docker/drupal-mysql
    ports:
      - "3306:3306"
    container_name: drupal-mysql