# Services required for Drupal - Apache, PHP-FPM, MySQL

version: '2'

services:

# Nginx container.
  drupal-nginx:
    container_name: drupal-nginx
    build:
      context: ./docker/drupal-nginx
    ports:
      - "8080:80"
    links:
      - drupal-php
    volumes:
      - .:/var/www

# PHP container.
  drupal-php:
    container_name: drupal-php
    build:
      context: ./docker/drupal-phpfpm
    ports:
      - "9001"
      - "9000:9000"
    links:
      - drupal-mysql
    env_file:
      - ./docker/drupal-phpfpm/conf/php-variables.env
    volumes:
      - .:/var/www
    volumes_from:
      - drupal-mysql

# MySQL container.
  drupal-mysql:
    container_name: drupal-mysql
    build:
      context: ./docker/drupal-mysql
    ports:
      - "3306:3306"
    env_file:
      - ./docker/drupal-mysql/conf/mysql-variables.env
    volumes:
      - /var/lib/mysql
      - /usr/bin

# DDD-CLI container.
  drupal-node:
    container_name: drupal-node
    build:
      context: ./docker/drupal-node
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock