# Additional services.

version: '2'

services:

# Drush container.
  drupal-drush:
    container_name: drupal-drush
    build:
      context: ./docker/drupal-drush
    external_links:
      - drupal-mysql
    volumes_from:
      - container:drupal-php
      - container:drupal-mysql
    networks:
      - drupaldockerdev_drupal-net

# Hook into network existing network.
networks:
  drupaldockerdev_drupal-net:
    external: true