# Services required for Drupal - Apache, PHP-FPM, MySQL

version: '2'

services:

# Nginx container.
  nginx:
    build:
      context: ./docker/drupal-nginx
    ports:
      - "8080:80"
    links:
      - drupal-php
    volumes:
      - .:/var/www
    container_name: drupal-nginx

# PHP container.
  drupal-php:
    build:
      context: ./docker/drupal-phpfpm
    ports:
      - "9001"
      - "9000:9000"
    links:
      - drupal-mysql
    container_name: drupal-php
    env_file:
      - ./docker/drupal-phpfpm/php-variables.env
    volumes:
      - .:/var/www
    volumes_from:
      - drupal-mysql

# MySQL container.
  drupal-mysql:
    build:
      context: ./docker/drupal-mysql
    ports:
      - "3306:3306"
    container_name: drupal-mysql
    env_file:
      - ./docker/drupal-mysql/mysql-variables.env
    volumes:
      - /var/lib/mysql
      - /usr/bin

## Apache container.
#  drupal-apache:
#    build:
#      context: ./docker/drupal-apache
#    ports:
#      - "8080:80"
#    volumes:
#      - .:/var/www
#    links:
#      - drupal-php
#    container_name: drupal-apache

## HHVM Composer container.
#  drupal-hhvm-composer:
#    build:
#      context: ./docker/drupal-hhvm-composer
#    volumes:
#      - .:/var/www
#      - ~/.composer/cache:/composer/cache
#    container_name: drupal-hhvm-composer