# Services required for Drupal - Apache, PHP-FPM, MySQL

version: '2'

services:
# Apache container.
  drupal-apache:
    build:
      context: ./docker/drupal-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    links:
      - drupal-php
    container_name: drupal-apache

# PHP container.
  drupal-php:
    build:
      context: ./docker/drupal-phpfpm
    ports:
      - "9001"
    volumes:
      - .:/var/www
    links:
      - drupal-mysql
    container_name: drupal-php

# MySQL image.
  drupal-mysql:
    build:
      context: ./docker/drupal-mysql
    ports:
      - "3306:3306"
    container_name: drupal-mysql
    env_file:
      - ./docker/drupal-mysql/mysql-variables.env

# HHVM Comopser container.
  drupal-hhvm-composer:
    build:
      context: ./docker/drupal-hhvm-composer
    volumes:
      - .:/var/www
      - ~/.composer/cache:/composer/cache
    container_name: drupal-hhvm-composer